branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

script:
  - Rscript -e 'rmarkdown::render_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: lccambiaghi/lccambiaghi.github.io
  target_branch: master
  # local_dir: public
  # fqdn: travis-blogdown.yihui.name
