# Site settings
title: Luca Cambiaghi
email: lc.cambiaghi@gmail.com
url: https://lccambiaghi.github.io
description: "Personal website of Luca Cambiaghi"
#skills: "Software Engineering - Data Science"
#meta_author: Cambiaghi Luca

# Google webmaster tools
#google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: lccambiaghi

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18BC9C
  primary-rgb: "24,188,156"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Luca Cambiaghi
  location: Location
  credits: Credits
  social: Social

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url:
  - title: facebook
    url:
  - title: instagram
    url:

# Postal address (add as many lines as necessary)
address:
  - line: Living in Kokkedal
  - line: Studying in Kongens Lyngby
  - line: Working in Copenhagen

# Credits content
credits: 'Credits to the Freelancer Theme for Bootstrap.'

# Build settings
markdown: kramdown
permalink: pretty
