name: Build and Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - snapshot
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: |
            echo "ENV=GHUB" >> $GITHUB_ENV
      - name: Download emacsd config
        run: |
            curl --output-dir pages/ -LO https://raw.githubusercontent.com/lccambiaghi/crafted-emacs-config/main/readme.org && \
            mv pages/readme.org pages/emacs.org
      - name: Download nix config
        run: |
            curl --output-dir pages/ -LO https://raw.githubusercontent.com/lccambiaghi/nixpkgs/main/readme.org && \
            mv pages/readme.org pages/nix.org
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - run: emacs --script /home/runner/work/lccambiaghi.github.io/lccambiaghi.github.io/publish.el
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: output # The folder the action should deploy.
